[package]
name = "kai-typecheck"
version.workspace = true
edition.workspace = true

[dependencies]
kai-ast = { workspace = true }
kai-tast = { workspace = true }
kai-diagnostics = { workspace = true }
kai-resolver = { workspace = true }

[dev-dependencies]
kai-lexer = { workspace = true }
kai-parser = { workspace = true }
