[package]
name = "kai-driver"
version.workspace = true
edition.workspace = true

[[bin]]
name = "kai"
path = "src/main.rs"

[dependencies]
kai-ast = { workspace = true }
kai-codegen = { workspace = true }
kai-diagnostics = { workspace = true }
kai-effects = { workspace = true }
kai-lexer = { workspace = true }
kai-ownership = { workspace = true }
kai-parser = { workspace = true }
kai-resolver = { workspace = true }
kai-tast = { workspace = true }
kai-typecheck = { workspace = true }
